sudo: false
language: java
jdk:
  - oraclejdk8
before_install:
install:
  - ./scripts/travis_install.sh
cache:
  directories:
    - $HOME/.m2
before_script:
script:
  - travis_wait ./scripts/travis_build.sh
notifications:
  slack: twigkit:PaqXnanM6oamkdAHZkadRSeo

# The following are currently unused build stages supplied by travis
# Note - adding these and using a blank value appears to trigger some default behaviour
#        for example resulting in deployment of artefacts which you may not want so be careful!

#after_success:
#after_failure:
#after_script:
#before_deploy:
#deploy:
#after_deploy: